version: '3'

services:

  dev:
    build:
      context: .
      dockerfile: docker/Dev.docker
    ports:
     - "8888:8888"
    command: pipenv run jupyter notebook --notebook-dir=/app/notebooks --ip='*' --allow-root --no-browser
    volumes:
      - ./bin:/app/bin
      - ./data:/app/data
      - ./notebooks:/app/notebooks
      - ./src:/app/src
      - ./tests:/app/tests
      - ./web:/app/web

  web:
    build:
      context: .
      dockerfile: docker/Web.docker
    env_file: credentials.env
    ports:
      - "5000:5000"
    command: pipenv run python /app/web/run.py
    volumes:
      - ./bin:/app/bin
      - ./src:/app/src
      - ./web:/app/web

